language: julia

julia:
  - 0.4
  - 0.5
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.clone(pwd())'
  - julia --check-bounds=yes --inline=no -e 'Pkg.test("IdentificationToolbox",
    coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("IdentificationToolbox")); Pkg.add("Coverage"); using Coverage;
    Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
